-- Phase A: additive multiplier premiums.
--
-- A category can now appear once standalone AND once per multiplier group on
-- the same card, so cards like Chase Freedom Flex can stack a permanent 2x
-- "dining premium" on Restaurants on top of the rotating group's 4x premium
-- on the same category. The unique constraint is replaced with two partial
-- unique indexes: at most one standalone row per (card, category), and at
-- most one row per (card, category, group).
--
-- is_additive on a multiplier (or group) marks the value as a *premium* that
-- adds onto the card's base + other applicable premiums, instead of
-- replacing them. Default false preserves the legacy "highest rate wins"
-- behavior for every existing card.
DO $$
DECLARE
    cons RECORD;
BEGIN
    ALTER TABLE card_category_multipliers
        ADD COLUMN IF NOT EXISTS is_additive BOOLEAN NOT NULL DEFAULT FALSE;

    ALTER TABLE card_multiplier_groups
        ADD COLUMN IF NOT EXISTS is_additive BOOLEAN NOT NULL DEFAULT FALSE;

    -- Drop EVERY unique constraint on card_category_multipliers whose column
    -- set is exactly (card_id, category_id). The constraint name is
    -- auto-generated by SQLAlchemy and we can't rely on it, so we walk
    -- pg_constraint and inspect conkey. This loop is idempotent: on a
    -- second run there's nothing to drop.
    FOR cons IN
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class cls ON cls.oid = con.conrelid
        WHERE cls.relname = 'card_category_multipliers'
          AND con.contype = 'u'
          AND (
              SELECT array_agg(att.attname::text ORDER BY att.attname::text)
              FROM unnest(con.conkey) AS k
              JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = k
          ) = ARRAY['card_id', 'category_id']::text[]
    LOOP
        RAISE NOTICE 'migration 024: dropping unique constraint %', cons.conname;
        EXECUTE 'ALTER TABLE card_category_multipliers DROP CONSTRAINT ' || quote_ident(cons.conname);
    END LOOP;

    -- Also drop any matching unique INDEX (SQLAlchemy 2.0 sometimes creates
    -- a plain index with the constraint name when you use UniqueConstraint).
    FOR cons IN
        SELECT i.relname AS conname
        FROM pg_index x
        JOIN pg_class i ON i.oid = x.indexrelid
        JOIN pg_class t ON t.oid = x.indrelid
        WHERE t.relname = 'card_category_multipliers'
          AND x.indisunique
          AND i.relname NOT IN ('uniq_ccm_standalone', 'uniq_ccm_grouped')
          AND (
              SELECT array_agg(att.attname::text ORDER BY att.attname::text)
              FROM unnest(x.indkey) AS k
              JOIN pg_attribute att ON att.attrelid = x.indrelid AND att.attnum = k
          ) = ARRAY['card_id', 'category_id']::text[]
          AND x.indpred IS NULL  -- skip partial indexes (the new ones we're creating)
    LOOP
        RAISE NOTICE 'migration 024: dropping unique index %', cons.conname;
        EXECUTE 'DROP INDEX ' || quote_ident(cons.conname);
    END LOOP;

    CREATE UNIQUE INDEX IF NOT EXISTS uniq_ccm_standalone
        ON card_category_multipliers(card_id, category_id)
        WHERE multiplier_group_id IS NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS uniq_ccm_grouped
        ON card_category_multipliers(card_id, category_id, multiplier_group_id)
        WHERE multiplier_group_id IS NOT NULL;
END $$;
